using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "3b1e3e84452b1971")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BaseCore</summary>
	[PublishedContentModel("baseCore")]
	public partial class BaseCore : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseCore";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseCore(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseCore, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>BasePage</summary>
	[PublishedContentModel("basePage")]
	public partial class BasePage : BaseCore
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "basePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HideFromMenu
		///</summary>
		[ImplementPropertyType("hideFromMenu")]
		public bool HideFromMenu
		{
			get { return this.GetPropertyValue<bool>("hideFromMenu"); }
		}

		///<summary>
		/// ImageCropper
		///</summary>
		[ImplementPropertyType("imageCropper")]
		public Umbraco.Web.Models.ImageCropDataSet ImageCropper
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("imageCropper"); }
		}

		///<summary>
		/// ShortDescription
		///</summary>
		[ImplementPropertyType("shortDescription_bg")]
		public string ShortDescription_bg
		{
			get { return this.GetPropertyValue<string>("shortDescription_bg"); }
		}

		///<summary>
		/// ShortDescription
		///</summary>
		[ImplementPropertyType("shortDescription_en")]
		public string ShortDescription_en
		{
			get { return this.GetPropertyValue<string>("shortDescription_en"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_bg")]
		public string Title_bg
		{
			get { return this.GetPropertyValue<string>("title_bg"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_en")]
		public string Title_en
		{
			get { return this.GetPropertyValue<string>("title_en"); }
		}
	}

	/// <summary>ContactUs</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address_bg")]
		public string Address_bg
		{
			get { return this.GetPropertyValue<string>("address_bg"); }
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address_en")]
		public string Address_en
		{
			get { return this.GetPropertyValue<string>("address_en"); }
		}

		///<summary>
		/// CardInformation
		///</summary>
		[ImplementPropertyType("cardInformation_bg")]
		public IHtmlString CardInformation_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("cardInformation_bg"); }
		}

		///<summary>
		/// CardInformation
		///</summary>
		[ImplementPropertyType("cardInformation_en")]
		public IHtmlString CardInformation_en
		{
			get { return this.GetPropertyValue<IHtmlString>("cardInformation_en"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email_bg")]
		public string Email_bg
		{
			get { return this.GetPropertyValue<string>("email_bg"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email_en")]
		public string Email_en
		{
			get { return this.GetPropertyValue<string>("email_en"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone_bg")]
		public string Phone_bg
		{
			get { return this.GetPropertyValue<string>("phone_bg"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone_en")]
		public string Phone_en
		{
			get { return this.GetPropertyValue<string>("phone_en"); }
		}
	}

	/// <summary>ContainerGeneral</summary>
	[PublishedContentModel("containerGeneral")]
	public partial class ContainerGeneral : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerGeneral";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerGeneral(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerGeneral, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerServices</summary>
	[PublishedContentModel("containerServices")]
	public partial class ContainerServices : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerServices";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerServices(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerServices, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// EighthRowTitle
		///</summary>
		[ImplementPropertyType("eighthRowTitle_bg")]
		public string EighthRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("eighthRowTitle_bg"); }
		}

		///<summary>
		/// EighthRowTitle
		///</summary>
		[ImplementPropertyType("eighthRowTitle_en")]
		public string EighthRowTitle_en
		{
			get { return this.GetPropertyValue<string>("eighthRowTitle_en"); }
		}

		///<summary>
		/// FifthRowTitle
		///</summary>
		[ImplementPropertyType("fifthRowTitle_bg")]
		public string FifthRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("fifthRowTitle_bg"); }
		}

		///<summary>
		/// FifthRowTitle
		///</summary>
		[ImplementPropertyType("fifthRowTitle_en")]
		public string FifthRowTitle_en
		{
			get { return this.GetPropertyValue<string>("fifthRowTitle_en"); }
		}

		///<summary>
		/// FirstRowTitle
		///</summary>
		[ImplementPropertyType("firstRowTitle_bg")]
		public string FirstRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("firstRowTitle_bg"); }
		}

		///<summary>
		/// FirstRowTitle
		///</summary>
		[ImplementPropertyType("firstRowTitle_en")]
		public string FirstRowTitle_en
		{
			get { return this.GetPropertyValue<string>("firstRowTitle_en"); }
		}

		///<summary>
		/// FourthRowTitle
		///</summary>
		[ImplementPropertyType("fourthRowTitle_bg")]
		public string FourthRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("fourthRowTitle_bg"); }
		}

		///<summary>
		/// FourthRowTitle
		///</summary>
		[ImplementPropertyType("fourthRowTitle_en")]
		public string FourthRowTitle_en
		{
			get { return this.GetPropertyValue<string>("fourthRowTitle_en"); }
		}

		///<summary>
		/// HideContainerDescription
		///</summary>
		[ImplementPropertyType("hideContainerDescription")]
		public bool HideContainerDescription
		{
			get { return this.GetPropertyValue<bool>("hideContainerDescription"); }
		}

		///<summary>
		/// HideContainerGallery
		///</summary>
		[ImplementPropertyType("hideContainerGallery")]
		public bool HideContainerGallery
		{
			get { return this.GetPropertyValue<bool>("hideContainerGallery"); }
		}

		///<summary>
		/// HideContainerHeader
		///</summary>
		[ImplementPropertyType("hideContainerHeader")]
		public bool HideContainerHeader
		{
			get { return this.GetPropertyValue<bool>("hideContainerHeader"); }
		}

		///<summary>
		/// HideContainerPriceBox
		///</summary>
		[ImplementPropertyType("hideContainerPriceBox")]
		public bool HideContainerPriceBox
		{
			get { return this.GetPropertyValue<bool>("hideContainerPriceBox"); }
		}

		///<summary>
		/// HideTableWithServices
		///</summary>
		[ImplementPropertyType("hideTableWithServices")]
		public bool HideTableWithServices
		{
			get { return this.GetPropertyValue<bool>("hideTableWithServices"); }
		}

		///<summary>
		/// ImageText
		///</summary>
		[ImplementPropertyType("imageText_bg")]
		public string ImageText_bg
		{
			get { return this.GetPropertyValue<string>("imageText_bg"); }
		}

		///<summary>
		/// ImageText
		///</summary>
		[ImplementPropertyType("imageText_en")]
		public string ImageText_en
		{
			get { return this.GetPropertyValue<string>("imageText_en"); }
		}

		///<summary>
		/// NinthRowTitle
		///</summary>
		[ImplementPropertyType("ninthRowTitle_bg")]
		public string NinthRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("ninthRowTitle_bg"); }
		}

		///<summary>
		/// NinthRowTitle
		///</summary>
		[ImplementPropertyType("ninthRowTitle_en")]
		public string NinthRowTitle_en
		{
			get { return this.GetPropertyValue<string>("ninthRowTitle_en"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_bg")]
		public IHtmlString RichTextEditor_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_bg"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_en")]
		public IHtmlString RichTextEditor_en
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_en"); }
		}

		///<summary>
		/// SecondRowTitle
		///</summary>
		[ImplementPropertyType("secondRowTitle_bg")]
		public string SecondRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("secondRowTitle_bg"); }
		}

		///<summary>
		/// SecondRowTitle
		///</summary>
		[ImplementPropertyType("secondRowTitle_en")]
		public string SecondRowTitle_en
		{
			get { return this.GetPropertyValue<string>("secondRowTitle_en"); }
		}

		///<summary>
		/// SeventhRowTitle
		///</summary>
		[ImplementPropertyType("seventhRowTitle_bg")]
		public string SeventhRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("seventhRowTitle_bg"); }
		}

		///<summary>
		/// SeventhRowTitle
		///</summary>
		[ImplementPropertyType("seventhRowTitle_en")]
		public string SeventhRowTitle_en
		{
			get { return this.GetPropertyValue<string>("seventhRowTitle_en"); }
		}

		///<summary>
		/// SixthRowTitle
		///</summary>
		[ImplementPropertyType("sixthRowTitle_bg")]
		public string SixthRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("sixthRowTitle_bg"); }
		}

		///<summary>
		/// SixthRowTitle
		///</summary>
		[ImplementPropertyType("sixthRowTitle_en")]
		public string SixthRowTitle_en
		{
			get { return this.GetPropertyValue<string>("sixthRowTitle_en"); }
		}

		///<summary>
		/// TenthRowTitle
		///</summary>
		[ImplementPropertyType("tenthRowTitle_bg")]
		public string TenthRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("tenthRowTitle_bg"); }
		}

		///<summary>
		/// TenthRowTitle
		///</summary>
		[ImplementPropertyType("tenthRowTitle_en")]
		public string TenthRowTitle_en
		{
			get { return this.GetPropertyValue<string>("tenthRowTitle_en"); }
		}

		///<summary>
		/// TextPriceTable
		///</summary>
		[ImplementPropertyType("textPriceTable_bg")]
		public string TextPriceTable_bg
		{
			get { return this.GetPropertyValue<string>("textPriceTable_bg"); }
		}

		///<summary>
		/// TextPriceTable
		///</summary>
		[ImplementPropertyType("textPriceTable_en")]
		public string TextPriceTable_en
		{
			get { return this.GetPropertyValue<string>("textPriceTable_en"); }
		}

		///<summary>
		/// ThirdRowTitle
		///</summary>
		[ImplementPropertyType("thirdRowTitle_bg")]
		public string ThirdRowTitle_bg
		{
			get { return this.GetPropertyValue<string>("thirdRowTitle_bg"); }
		}

		///<summary>
		/// ThirdRowTitle
		///</summary>
		[ImplementPropertyType("thirdRowTitle_en")]
		public string ThirdRowTitle_en
		{
			get { return this.GetPropertyValue<string>("thirdRowTitle_en"); }
		}
	}

	/// <summary>ContainerServicesWrap</summary>
	[PublishedContentModel("containerServicesWrap")]
	public partial class ContainerServicesWrap : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerServicesWrap";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerServicesWrap(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerServicesWrap, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HideContainerDescription
		///</summary>
		[ImplementPropertyType("hideContainerDescription")]
		public bool HideContainerDescription
		{
			get { return this.GetPropertyValue<bool>("hideContainerDescription"); }
		}

		///<summary>
		/// HideContainerGallery
		///</summary>
		[ImplementPropertyType("hideContainerGallery")]
		public bool HideContainerGallery
		{
			get { return this.GetPropertyValue<bool>("hideContainerGallery"); }
		}

		///<summary>
		/// HideContainerHeader
		///</summary>
		[ImplementPropertyType("hideContainerHeader")]
		public bool HideContainerHeader
		{
			get { return this.GetPropertyValue<bool>("hideContainerHeader"); }
		}

		///<summary>
		/// HideContainerPriceBox
		///</summary>
		[ImplementPropertyType("hideContainerPriceBox")]
		public bool HideContainerPriceBox
		{
			get { return this.GetPropertyValue<bool>("hideContainerPriceBox"); }
		}

		///<summary>
		/// HideTableWithServices
		///</summary>
		[ImplementPropertyType("hideTableWithServices")]
		public bool HideTableWithServices
		{
			get { return this.GetPropertyValue<bool>("hideTableWithServices"); }
		}

		///<summary>
		/// ImageText
		///</summary>
		[ImplementPropertyType("imageText_bg")]
		public string ImageText_bg
		{
			get { return this.GetPropertyValue<string>("imageText_bg"); }
		}

		///<summary>
		/// ImageText
		///</summary>
		[ImplementPropertyType("imageText_en")]
		public string ImageText_en
		{
			get { return this.GetPropertyValue<string>("imageText_en"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_bg")]
		public IHtmlString RichTextEditor_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_bg"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_en")]
		public IHtmlString RichTextEditor_en
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_en"); }
		}
	}

	/// <summary>ContainerSoftware</summary>
	[PublishedContentModel("containerSoftware")]
	public partial class ContainerSoftware : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerSoftware";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerSoftware(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerSoftware, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>GenericPage</summary>
	[PublishedContentModel("genericPage")]
	public partial class GenericPage : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "genericPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenericPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_bg")]
		public IHtmlString RichTextEditor_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_bg"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_en")]
		public IHtmlString RichTextEditor_en
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_en"); }
		}
	}

	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HideContCollectionService
		///</summary>
		[ImplementPropertyType("hideContCollectionService")]
		public bool HideContCollectionService
		{
			get { return this.GetPropertyValue<bool>("hideContCollectionService"); }
		}

		///<summary>
		/// HideContCollectionSoftware
		///</summary>
		[ImplementPropertyType("hideContCollectionSoftware")]
		public bool HideContCollectionSoftware
		{
			get { return this.GetPropertyValue<bool>("hideContCollectionSoftware"); }
		}

		///<summary>
		/// HideContGalleryService
		///</summary>
		[ImplementPropertyType("hideContGalleryService")]
		public bool HideContGalleryService
		{
			get { return this.GetPropertyValue<bool>("hideContGalleryService"); }
		}

		///<summary>
		/// HideContGallerySoftware
		///</summary>
		[ImplementPropertyType("hideContGallerySoftware")]
		public bool HideContGallerySoftware
		{
			get { return this.GetPropertyValue<bool>("hideContGallerySoftware"); }
		}

		///<summary>
		/// HomeImageText
		///</summary>
		[ImplementPropertyType("homeImageText_bg")]
		public string HomeImageText_bg
		{
			get { return this.GetPropertyValue<string>("homeImageText_bg"); }
		}

		///<summary>
		/// HomeImageText
		///</summary>
		[ImplementPropertyType("homeImageText_en")]
		public string HomeImageText_en
		{
			get { return this.GetPropertyValue<string>("homeImageText_en"); }
		}
	}

	/// <summary>Service</summary>
	[PublishedContentModel("service")]
	public partial class Service : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "service";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Service(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Service, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// EighthRowBody
		///</summary>
		[ImplementPropertyType("eighthRowBody_bg")]
		public string EighthRowBody_bg
		{
			get { return this.GetPropertyValue<string>("eighthRowBody_bg"); }
		}

		///<summary>
		/// EighthRowBody
		///</summary>
		[ImplementPropertyType("eighthRowBody_en")]
		public string EighthRowBody_en
		{
			get { return this.GetPropertyValue<string>("eighthRowBody_en"); }
		}

		///<summary>
		/// EighthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("eighthRowBodyRadioButtonList_bg")]
		public int EighthRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("eighthRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// EighthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("eighthRowBodyRadioButtonList_en")]
		public int EighthRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("eighthRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// FifthRowBody
		///</summary>
		[ImplementPropertyType("fifthRowBody_bg")]
		public string FifthRowBody_bg
		{
			get { return this.GetPropertyValue<string>("fifthRowBody_bg"); }
		}

		///<summary>
		/// FifthRowBody
		///</summary>
		[ImplementPropertyType("fifthRowBody_en")]
		public string FifthRowBody_en
		{
			get { return this.GetPropertyValue<string>("fifthRowBody_en"); }
		}

		///<summary>
		/// FifthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("fifthRowBodyRadioButtonList_bg")]
		public int FifthRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("fifthRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// FifthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("fifthRowBodyRadioButtonList_en")]
		public int FifthRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("fifthRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// FirstRowBody
		///</summary>
		[ImplementPropertyType("firstRowBody_bg")]
		public string FirstRowBody_bg
		{
			get { return this.GetPropertyValue<string>("firstRowBody_bg"); }
		}

		///<summary>
		/// FirstRowBody
		///</summary>
		[ImplementPropertyType("firstRowBody_en")]
		public string FirstRowBody_en
		{
			get { return this.GetPropertyValue<string>("firstRowBody_en"); }
		}

		///<summary>
		/// FirstRowBodyRadioList
		///</summary>
		[ImplementPropertyType("firstRowBodyRadioButtonList_bg")]
		public int FirstRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("firstRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// FirstRowBodyRadioList
		///</summary>
		[ImplementPropertyType("firstRowBodyRadioButtonList_en")]
		public int FirstRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("firstRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// FourthRowBody
		///</summary>
		[ImplementPropertyType("fourthRowBody_bg")]
		public string FourthRowBody_bg
		{
			get { return this.GetPropertyValue<string>("fourthRowBody_bg"); }
		}

		///<summary>
		/// FourthRowBody
		///</summary>
		[ImplementPropertyType("fourthRowBody_en")]
		public string FourthRowBody_en
		{
			get { return this.GetPropertyValue<string>("fourthRowBody_en"); }
		}

		///<summary>
		/// FourtRowBodyRadioList
		///</summary>
		[ImplementPropertyType("fourtRowBodyRadioButtonList_bg")]
		public int FourtRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("fourtRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// FourtRowBodyRadioList
		///</summary>
		[ImplementPropertyType("fourtRowBodyRadioButtonList_en")]
		public int FourtRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("fourtRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// NinthRowBody
		///</summary>
		[ImplementPropertyType("ninthRowBody_bg")]
		public string NinthRowBody_bg
		{
			get { return this.GetPropertyValue<string>("ninthRowBody_bg"); }
		}

		///<summary>
		/// NinthRowBody
		///</summary>
		[ImplementPropertyType("ninthRowBody_en")]
		public string NinthRowBody_en
		{
			get { return this.GetPropertyValue<string>("ninthRowBody_en"); }
		}

		///<summary>
		/// NinthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("ninthRowBodyRadioButtonList_bg")]
		public int NinthRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("ninthRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// NinthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("ninthRowBodyRadioButtonList_en")]
		public int NinthRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("ninthRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// Period
		///</summary>
		[ImplementPropertyType("period_bg")]
		public string Period_bg
		{
			get { return this.GetPropertyValue<string>("period_bg"); }
		}

		///<summary>
		/// Period
		///</summary>
		[ImplementPropertyType("period_en")]
		public string Period_en
		{
			get { return this.GetPropertyValue<string>("period_en"); }
		}

		///<summary>
		/// PriceForThePeriod
		///</summary>
		[ImplementPropertyType("priceForThePeriod_bg")]
		public string PriceForThePeriod_bg
		{
			get { return this.GetPropertyValue<string>("priceForThePeriod_bg"); }
		}

		///<summary>
		/// PriceForThePeriod
		///</summary>
		[ImplementPropertyType("priceForThePeriod_en")]
		public string PriceForThePeriod_en
		{
			get { return this.GetPropertyValue<string>("priceForThePeriod_en"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_bg")]
		public IHtmlString RichTextEditor_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_bg"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_en")]
		public IHtmlString RichTextEditor_en
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_en"); }
		}

		///<summary>
		/// SecondRowBody
		///</summary>
		[ImplementPropertyType("secondRowBody_bg")]
		public string SecondRowBody_bg
		{
			get { return this.GetPropertyValue<string>("secondRowBody_bg"); }
		}

		///<summary>
		/// SecondRowBody
		///</summary>
		[ImplementPropertyType("secondRowBody_en")]
		public string SecondRowBody_en
		{
			get { return this.GetPropertyValue<string>("secondRowBody_en"); }
		}

		///<summary>
		/// SecondRowBodyRadioList
		///</summary>
		[ImplementPropertyType("secondRowBodyRadioButtonList_bg")]
		public int SecondRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("secondRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// SecondRowBodyRadioList
		///</summary>
		[ImplementPropertyType("secondRowBodyRadioButtonList_en")]
		public int SecondRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("secondRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// SeventhRowBody
		///</summary>
		[ImplementPropertyType("seventhRowBody_bg")]
		public string SeventhRowBody_bg
		{
			get { return this.GetPropertyValue<string>("seventhRowBody_bg"); }
		}

		///<summary>
		/// SeventhRowBody
		///</summary>
		[ImplementPropertyType("seventhRowBody_en")]
		public string SeventhRowBody_en
		{
			get { return this.GetPropertyValue<string>("seventhRowBody_en"); }
		}

		///<summary>
		/// SeventhRowBodyRadioList
		///</summary>
		[ImplementPropertyType("seventhRowBodyRadioButtonList_bg")]
		public int SeventhRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("seventhRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// SeventhRowBodyRadioList
		///</summary>
		[ImplementPropertyType("seventhRowBodyRadioButtonList_en")]
		public int SeventhRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("seventhRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// SixthRowBody
		///</summary>
		[ImplementPropertyType("sixthRowBody_bg")]
		public string SixthRowBody_bg
		{
			get { return this.GetPropertyValue<string>("sixthRowBody_bg"); }
		}

		///<summary>
		/// SixthRowBody
		///</summary>
		[ImplementPropertyType("sixthRowBody_en")]
		public string SixthRowBody_en
		{
			get { return this.GetPropertyValue<string>("sixthRowBody_en"); }
		}

		///<summary>
		/// SixthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("sixthRowBodyRadioButtonList_bg")]
		public int SixthRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("sixthRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// SixthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("sixthRowBodyRadioButtonList_en")]
		public int SixthRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("sixthRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// TenthRowBody
		///</summary>
		[ImplementPropertyType("tenthRowBody_bg")]
		public string TenthRowBody_bg
		{
			get { return this.GetPropertyValue<string>("tenthRowBody_bg"); }
		}

		///<summary>
		/// TenthRowBody
		///</summary>
		[ImplementPropertyType("tenthRowBody_en")]
		public string TenthRowBody_en
		{
			get { return this.GetPropertyValue<string>("tenthRowBody_en"); }
		}

		///<summary>
		/// TenthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("tenthRowBodyRadioButtonList_bg")]
		public int TenthRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("tenthRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// TenthRowBodyRadioList
		///</summary>
		[ImplementPropertyType("tenthRowBodyRadioButtonList_en")]
		public int TenthRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("tenthRowBodyRadioButtonList_en"); }
		}

		///<summary>
		/// ThirdRowBody
		///</summary>
		[ImplementPropertyType("thirdRowBody_bg")]
		public string ThirdRowBody_bg
		{
			get { return this.GetPropertyValue<string>("thirdRowBody_bg"); }
		}

		///<summary>
		/// ThirdRowBody
		///</summary>
		[ImplementPropertyType("thirdRowBody_en")]
		public string ThirdRowBody_en
		{
			get { return this.GetPropertyValue<string>("thirdRowBody_en"); }
		}

		///<summary>
		/// ThirdRowBodyRadioList
		///</summary>
		[ImplementPropertyType("thirdRowBodyRadioButtonList_bg")]
		public int ThirdRowBodyRadioButtonList_bg
		{
			get { return this.GetPropertyValue<int>("thirdRowBodyRadioButtonList_bg"); }
		}

		///<summary>
		/// ThirdRowBodyRadioList
		///</summary>
		[ImplementPropertyType("thirdRowBodyRadioButtonList_en")]
		public int ThirdRowBodyRadioButtonList_en
		{
			get { return this.GetPropertyValue<int>("thirdRowBodyRadioButtonList_en"); }
		}
	}

	/// <summary>Software</summary>
	[PublishedContentModel("software")]
	public partial class Software : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "software";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Software(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Software, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// MediaPicker
		///</summary>
		[ImplementPropertyType("mediaPicker")]
		public IEnumerable<IPublishedContent> MediaPicker
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("mediaPicker"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_bg")]
		public IHtmlString RichTextEditor_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_bg"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_en")]
		public IHtmlString RichTextEditor_en
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_en"); }
		}
	}

	// Mixin content Type 1297 with alias "googleAnalyticsEventBase"
	/// <summary>Event Base</summary>
	public partial interface IGoogleAnalyticsEventBase : IPublishedContent
	{
		/// <summary>Category</summary>
		string GoogleAnalyticsEvent_Category { get; }

		/// <summary>CSS Selector</summary>
		string GoogleAnalyticsEvent_CssSelector { get; }
	}

	/// <summary>Event Base</summary>
	[PublishedContentModel("googleAnalyticsEventBase")]
	public partial class GoogleAnalyticsEventBase : PublishedContentModel, IGoogleAnalyticsEventBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "googleAnalyticsEventBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GoogleAnalyticsEventBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GoogleAnalyticsEventBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category: The category the event should be classified in the Google Analytics dashboard
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Category")]
		public string GoogleAnalyticsEvent_Category
		{
			get { return GetGoogleAnalyticsEvent_Category(this); }
		}

		/// <summary>Static getter for Category</summary>
		public static string GetGoogleAnalyticsEvent_Category(IGoogleAnalyticsEventBase that) { return that.GetPropertyValue<string>("googleAnalyticsEvent_Category"); }

		///<summary>
		/// CSS Selector: The CSS selector that will be used to attach the GA event to the element. Example: ".someClass", "#some-id", "h1"{br /}{br /} Don't know CSS? {a href="https://codelaborators-network.github.io/Google-Analytics-Events-for-Umbraco/" target="_blank" title="Opens in new tab"}Check out the documentation for more examples{/a}
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_CssSelector")]
		public string GoogleAnalyticsEvent_CssSelector
		{
			get { return GetGoogleAnalyticsEvent_CssSelector(this); }
		}

		/// <summary>Static getter for CSS Selector</summary>
		public static string GetGoogleAnalyticsEvent_CssSelector(IGoogleAnalyticsEventBase that) { return that.GetPropertyValue<string>("googleAnalyticsEvent_CssSelector"); }
	}

	/// <summary>Advanced Event</summary>
	[PublishedContentModel("googleAnalyticsEventItem")]
	public partial class GoogleAnalyticsEventItem : PublishedContentModel, IGoogleAnalyticsEventBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "googleAnalyticsEventItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GoogleAnalyticsEventItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GoogleAnalyticsEventItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Action: The action type that you are listening for on the element. Example: The "click" action will fire when an element is clicked
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Action")]
		public object GoogleAnalyticsEvent_Action
		{
			get { return this.GetPropertyValue("googleAnalyticsEvent_Action"); }
		}

		///<summary>
		/// Label: The label to use for the GA event.{br /}{br /} Please note that this is templatable. Simple enter one of the following placeholders and it will be replaced by the appropriate value when the vent takes place: {br /}{br /}PageUrl: {PAGE_URL}, PageRelativeUrl: {PAGE_RELATIVE_URL}, TagName: {TAG_NAME}, ID: {ID} , Class: {CLASS}, Value: {VALUE}, Src: {SRC}, LinkUrl: {LINK_URL}, LinkRelativeUrl: {LINK_RELATIVE_URL}, Alt: {ALT}, Title: {TITLE}, InnerHTML: {INNER_HTML}. {br /}{br /} Still confused? {a href="https://codelaborators-network.github.io/Google-Analytics-Events-for-Umbraco/" target="_blank" title="Opens in new tab"}Check out the documentation for more detailed guides{/a}
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Label")]
		public string GoogleAnalyticsEvent_Label
		{
			get { return this.GetPropertyValue<string>("googleAnalyticsEvent_Label"); }
		}

		///<summary>
		/// Category: The category the event should be classified in the Google Analytics dashboard
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Category")]
		public string GoogleAnalyticsEvent_Category
		{
			get { return Umbraco.Web.PublishedContentModels.GoogleAnalyticsEventBase.GetGoogleAnalyticsEvent_Category(this); }
		}

		///<summary>
		/// CSS Selector: The CSS selector that will be used to attach the GA event to the element. Example: ".someClass", "#some-id", "h1"{br /}{br /} Don't know CSS? {a href="https://codelaborators-network.github.io/Google-Analytics-Events-for-Umbraco/" target="_blank" title="Opens in new tab"}Check out the documentation for more examples{/a}
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_CssSelector")]
		public string GoogleAnalyticsEvent_CssSelector
		{
			get { return Umbraco.Web.PublishedContentModels.GoogleAnalyticsEventBase.GetGoogleAnalyticsEvent_CssSelector(this); }
		}
	}

	/// <summary>Google Analytics Tracking</summary>
	[PublishedContentModel("googleAnalyticsEventRoot")]
	public partial class GoogleAnalyticsEventRoot : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "googleAnalyticsEventRoot";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GoogleAnalyticsEventRoot(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GoogleAnalyticsEventRoot, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disable GA Events: Settings this flag will disable all events on all pages.
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_DisableEvents")]
		public bool GoogleAnalyticsEvent_DisableEvents
		{
			get { return this.GetPropertyValue<bool>("googleAnalyticsEvent_DisableEvents"); }
		}

		///<summary>
		/// Google Analytics Key: Enter your unique GA property id here to be used on the page
		///</summary>
		[ImplementPropertyType("googleAnalyticsKey")]
		public string GoogleAnalyticsKey
		{
			get { return this.GetPropertyValue<string>("googleAnalyticsKey"); }
		}
	}

	/// <summary>Standard Event</summary>
	[PublishedContentModel("googleAnalyticsStandardEvent")]
	public partial class GoogleAnalyticsStandardEvent : PublishedContentModel, IGoogleAnalyticsEventBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "googleAnalyticsStandardEvent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GoogleAnalyticsStandardEvent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GoogleAnalyticsStandardEvent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Action: The action type that you are listening for on the element. Example: The "click" action will fire when an element is clicked
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Action")]
		public object GoogleAnalyticsEvent_Action
		{
			get { return this.GetPropertyValue("googleAnalyticsEvent_Action"); }
		}

		///<summary>
		/// Label: Choose which information you would like to appear in the label in Google Analytics. If you want more control of this, create a Google Analytics Advanced Event instead.
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Label")]
		public IEnumerable<string> GoogleAnalyticsEvent_Label
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("googleAnalyticsEvent_Label"); }
		}

		///<summary>
		/// Category: The category the event should be classified in the Google Analytics dashboard
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_Category")]
		public string GoogleAnalyticsEvent_Category
		{
			get { return Umbraco.Web.PublishedContentModels.GoogleAnalyticsEventBase.GetGoogleAnalyticsEvent_Category(this); }
		}

		///<summary>
		/// CSS Selector: The CSS selector that will be used to attach the GA event to the element. Example: ".someClass", "#some-id", "h1"{br /}{br /} Don't know CSS? {a href="https://codelaborators-network.github.io/Google-Analytics-Events-for-Umbraco/" target="_blank" title="Opens in new tab"}Check out the documentation for more examples{/a}
		///</summary>
		[ImplementPropertyType("googleAnalyticsEvent_CssSelector")]
		public string GoogleAnalyticsEvent_CssSelector
		{
			get { return Umbraco.Web.PublishedContentModels.GoogleAnalyticsEventBase.GetGoogleAnalyticsEvent_CssSelector(this); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
